#!/bin/bash

# sudo apt install -y protobuf-compiler
# go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
# sudo apt install -y upx

set -e

declare PROTO_DIR="./protobuf"
declare BIN="./med"
declare TARGET="$1"
declare TAGS=""

shift
if [[ $# == 0 ]]; then
    TAGS="client server keygen"
else
    for tag in "$@"; do
        TAGS="$TAGS $tag"
    done
    TAGS="${TAGS#,}"
    echo "tags = $TAGS"
fi

case "$TARGET" in
    debug) (
        rm -fv "$BIN"
        set -x
        protoc -I="$PROTO_DIR" --go_out=. "$PROTO_DIR/med.proto"
        go build -tags="$TAGS dev" -o "$BIN" ./main.go
    ) ;;
    release) (
        rm -fv "$BIN"
        set -x
        protoc -I="$PROTO_DIR" --go_out=. "$PROTO_DIR/med.proto"
        go build -ldflags="-s -w" -tags="$TAGS" -o "$BIN" ./main.go
        upx -9 "$BIN"
    ) ;;
    *)
        >&2 echo "error: unexpected target: $TARGET"
        exit 1
        ;;
esac
